### PR TITLE
Adds a setting in "ruboto.yml" for the desired dex_heap_size

### PR DESCRIPTION
**Pull request by lucasallan**
This is a work in progress - I haven't properly tested it yet. I just wanna know if I'm in the right direction.

Related to https://github.com/ruboto/ruboto/issues/778
Thanks!

### CODE REVIEW

**Comment by donv** [comment]
Hi @lucasallan !

It looks like you are on the right track.  Add a test, and we can merge.  I am working on getting master green with SSL support, so you may have to rebase.

**Comment by lucasallan** [comment]
@donv Thanks! I'll add a test case soon (probably tomorrow or Wednesday - busy Monday).

**Comment by donv** [comment]
Hi @lucasallan !

How is the test case coming along?

**Comment by lucasallan** [comment]
Hi @donv, I haven't had chance to work on it yet. I'll do asap!

**Comment by donv** [comment]
Great!  Looking forward to it!

**Comment by lucasallan** [comment]
I'm having a hard time to run `rake test` it appears to just hang.

```
➜  ruboto git:(heap_size) ✗ rake test
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 25.73-b02 on 1.8.0_73-b02 [darwin-x86_64]
Reading OS version from device/emulator
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
```

**Comment by donv** [comment]
Hi @lucasallan !

Sorry for not getting back to you sooner.  Got a new job!

How are you doing with this?  How can I help?

**Pull request merged**
