### PR TITLE
rake log task detects activity start on lollipop

### PR DESCRIPTION
**Pull request by gfowley**
Android lollipop changed ActivityManager logging for activity start. It was not detected by rake log task, so no log was displayed. I added a regex to detect the new log record.

### CODE REVIEW

**Comment by gfowley** [comment]
CI is failing because I initially forked from a failing Ruboto master. Okay to merge after manual review ( there are no tests for "rake log" ) ? ...or should I go again from a passing Ruboto master ?

**Comment by danielpassos** [comment]
I prefer do a quickly rebase first. only to we have a historical PR green/pass. wdyt?

```
git remote add forked git@github.com:ruboto/ruboto.git
git fetch forked
git rebase forked/master
git push origin master
```

**Comment by gfowley** [comment]
Will do. I was looking for a way to do that in GitHub, thanks for the git details.

**Comment by donv** [comment]
Thanks @gfowley !

**Pull request merged**
